export const RpRoutes = {
    'ADOPT': 'ADOPT',
    'ADMIN': 'ADMIN',
    'LOGIN': 'LOGIN',
    'REGISTER': 'REGISTER',
    'ADMIN_USERS': 'ADMIN_USERS',
    'ADMIN_ORGANIZATIONS': 'ADMIN_ORGANIZATIONS',
    'ADMIN_ROLES': 'ADMIN_ROLES',
    'ADMIN_ANIMAL_TYPES': 'ADMIN_ANIMAL_TYPES',
    'ADMIN_ANIMAL_SIZES': 'ADMIN_ANIMAL_SIZES',
}